/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DateTimePickerC3: typeof import('./src/components/DateTimePickerC3.vue')['default']
    FormItems: typeof import('./src/components/FormItems.vue')['default']
    FormItemsEditable: typeof import('./src/components/FormItemsEditable.vue')['default']
    ImageManager: typeof import('./src/components/ImageManager.vue')['default']
    Lightbox: typeof import('./src/components/Lightbox.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    NoItemsFound: typeof import('./src/components/NoItemsFound.vue')['default']
    PageTitle: typeof import('./src/components/PageTitle.vue')['default']
    Phone: typeof import('./src/components/Phone.vue')['default']
    ProgressLoader: typeof import('./src/components/ProgressLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimePicker: typeof import('./src/components/TimePicker.vue')['default']
    UserAvatar: typeof import('./src/components/UserAvatar.vue')['default']
  }
}
